services:
  backend:
    container_name: angular-todos-backend
    restart: unless-stopped
    image: dafnik/angular-todos-backend:latest
    ports:
      - "8080:8080"
    volumes:
      - angular-todos-backend:/var/lib/angular-todos
    environment:
      - AUTH_KEYS_DIRECTORY=/var/lib/angular-todos/authentication-keys
    networks:
      - angular-todos-backend
    # No healthcheck possible as the container is distroless and therefore has no bash nor other tools to make requests

volumes:
  angular-todos-backend:

networks:
  angular-todos-backend:

