server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: todo
  main:
    allow-bean-definition-overriding: true

auth:
  keys:
    directory: ${AUTH_KEYS_DIRECTORY}
    user:
      access-token:
        private: ${AUTH_KEYS_DIRECTORY}/user-access-token-private.key
        public: ${AUTH_KEYS_DIRECTORY}/user-access-token-public.key
      refresh-token:
        private: ${AUTH_KEYS_DIRECTORY}/user-refresh-token-private.key
        public: ${AUTH_KEYS_DIRECTORY}/user-refresh-token-public.key

springdoc:
  api-docs:
    enabled: true
    path: /swagger/docs-api
  swagger-ui:
    path: /swagger/docs
  packagesToScan: me.dafnik

logging:
  level:
    me.dafnik: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG