name: Build, test jar and create docker image for monolith service

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build -x test -Pversion=${{ github.ref_name }} -Dspring.profiles.active=container --scan --no-daemon

      - name: Archive jar artifacts
        uses: actions/upload-artifact@v4
        with:
          name: monolith-jar
          path: ./build/libs/
          retention-days: 1

  build-publish-docker:
    needs: build-jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download a single jar artifact
        uses: actions/download-artifact@v4
        with:
          name: monolith-jar
          path: ./build/libs/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push prod Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            version=${{ github.ref_name }}
          tags: |
            ghcr.io/dafnik/angular-todos-backend:${{ github.ref_name }}
            ghcr.io/dafnik/angular-todos:latest
